In [5]:
import numpy as np

arr = []
i = 0
j = 0

while j < 2:
    while True:
        a = int(input())
        if a == -1:
            break
        arr.append(a)
        i = i + 1
    if j == 0:
        exam1 = np.array(arr).reshape(int(i/3), 3)
    else:
        exam2 = np.array(arr).reshape(int(i/3), 3)
    arr.clear()
    i = 0
    j = j + 1

j = 0
score_arr = np.zeros((exam1.shape[0],3))
for i in range(0, exam1.shape[0]):
    for j in range(0, exam1.shape[1]):
        score = round((exam1[i][j] + exam2[i][j]) / 2, 2)
        if j == 0:
            score_arr[i][j] = score + 10
        elif score < 60:
            score_arr[i][j] = -1
        else:
            score_arr[i][j] = score

print(exam1)
print()
print(exam2)
print()
print(score_arr)

[[ 65  70  85]
 [ 90 100  70]
 [ 70  50  20]]

[[80 90 60]
 [30 95 60]
 [75 20 80]]

[[82.5 80.  72.5]
 [70.  97.5 65. ]
 [82.5 -1.  -1. ]]
